name: THIS ONE

on:
  push:
    branches:
      - main

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x

    - name: Install dependencies
      run: pip install -r requirements.txt
      working-directory: ${{ github.workspace }}

    - name: Run Python script
      env:
        GITHUB_ORG: "erasmolpaorg"
        GITHUB_ACCESS_TOKEN: ${{ secrets.ADMIN_TOKEN }}
        GITHUB_BACKUP_DIR: ${{ github.workspace }}
      run: python gh_backup.py $GITHUB_ORG $GITHUB_ACCESS_TOKEN $GITHUB_BACKUP_DIR
      working-directory: ${{ github.workspace }}
      
    - name: Commit and Push
      env:
        GIT_USERNAME: ${{ secrets.ADMIN_USER_NAME }}
        GIT_USER_EMAIL: ${{ secrets.ADMIN_USER_EMAIL }}
        GIT_TOKEN: ${{ secrets.ADMIN_TOKEN }}
      run: |
        git config user.name "${GIT_USERNAME}"
        git config user.email "${GIT_EMAIL}"
        git add *
        git commit -m "Auto commit from GitHub Action"
        git push
